#Requires AutoHotkey v2.0



CentralCity() {
    Sleep(1579)
Send("{d down}")
Sleep(250)
Send("{d up}")
Sleep(1187)
Send("{w down}")
Sleep(1203)
Send("{w up}")
Sleep(891)
Send("{a down}")
Sleep(203)
Send("{a up}")
Sleep(1016)
Send("{w down}")
Sleep(718)
Send("{w up}")
Sleep(594)
Send("{w down}")
Sleep(2172)
Send("{w up}")
Sleep(375)
Send("{a down}")
Sleep(734)
Send("{a up}")
Sleep(407)
Send("{w down}")
Sleep(171)
Send("{w up}")
Sleep(266)
Send("{w down}")
Sleep(109)
Send("{w up}")
Sleep(1000)
Send("{w down}")
Sleep(16)
Send("{w up}")

}


U18Movement() {
    ; Walking Movement Script Generated by AHK

Sleep(1812)
Send("{d down}")
Sleep(469)
Send("{d up}")
Sleep(250)
Send("{d down}")
Sleep(406)
Send("{d up}")
Sleep(579)
Send("{s down}")
Sleep(453)
Send("{s up}")
Sleep(687)
Send("{d down}")
Sleep(2063)
Send("{d up}")
Sleep(500)
Send("{d down}")
Sleep(47)
Send("{d up}")
Sleep(468)
Send("{d down}")
Sleep(16)
Send("{d up}")
Sleep(750)
Send("{d down}")
Sleep(16)
Send("{d up}")


}